### ISSUE TITLE
Property "text-rendering" doesn't exist

### ISSUE THREAD

**Issue by Alecto** [sparksuite/w3c-css-validator#135]
the validator swears at this line of code...
![image](https://user-images.githubusercontent.com/8464662/184890322-bab0b1f0-f79a-4090-96b8-c61b56a939f6.png)
![image](https://user-images.githubusercontent.com/8464662/184890413-d297527b-b1ef-454f-aae7-fa9f981709bb.png)

standard font awesome 4.7 style is used
```
.fa {
  display: inline-block;

  font: normal normal normal 14px/1 FontAwesome;
  font-size: inherit;

  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-rendering: auto;
}
```

online validation passes without errors
![image](https://user-images.githubusercontent.com/8464662/184890715-347cd803-1f05-4094-bea2-3c3aefcca64c.png)

**Comment by corymharper** [comment]
That is because the profile we currently use when making requests to the W3C CSS Validator API is `css3` the value you used when entering it on their website is `css3svg`. Thats not a profile value that they document: https://jigsaw.w3.org/css-validator/manual.html#requestformat, but it is one that they use. We could consider using it, or at least creating an option to allow a change in profile, but thats the cause of the error you are seeing. `text-rendering` is not specified by the CSS specification, but rather by the SVG specification.

**Comment by Alecto** [comment]
@corymharper 
understood thanks.
Is it possible to switch the validation to css3svg in the plugin?
I didn't find such an option in the documentation.
this is important because bootstrap, font-awesome... validation gives errors, which is not the default (css3 + svg) in the online validator.
thanks for the help.

**Comment by WesCossick** [comment]
Superseded by https://github.com/sparksuite/w3c-css-validator/issues/143.
