### ISSUE TITLE
Ensure testing tests the browser environment too

### ISSUE THREAD

**Issue by WesCossick** [sparksuite/w3c-css-validator#15]
Right now, our testing ensures the code works in Node.js, but we should also prove that it works in a browser environment too.

**Comment by WesCossick** [comment]
We may need to incorporate a headless browser somehow like we did with: https://github.com/sparksuite/react-accessible-dropdown-menu-hook...

**Comment by corymharper** [comment]
I think Puppeteer is probably our best bet, since we really want a fetch to be made to test the result... on the implementation side, in https://github.com/sparksuite/react-accessible-dropdown-menu-hook we had a demo website that puppeteer also used for it's tests. Will we be wanting to do something similar here, or should we keep it to a much smaller scale.

**Comment by WesCossick** [comment]
> Will we be wanting to do something similar here, or should we keep it to a much smaller scale.

Let's try to keep the implementation pretty minimal; just enough to show it works in a browser environment.
