### ISSUE TITLE
Property “clip-path” doesn't exist

### ISSUE THREAD

**Issue by raoufswe** [sparksuite/w3c-css-validator#174]
Hi there, thank you for your effort in maintaining the library 🌟 

I might be missing something but using `clip-path` seems to throw an invalid error while most modern browsers support that. 

example:

```
.foo {
    clip-path: inset(1px)
}
```

**Comment by corymharper** [comment]
Hey @raoufswe, thanks for your interest in our package. I looked into this, the reason it is being called out as invalid is because we internally pass a `profile` parameter of `css3` to the validator API, and I'm guessing for reasons of the specifications these rules are established under, the validator separately supports the rule you mention in an undocumented profile of `css3svg`. I think the most straightforward way for us to implement support for this would be to resolve #143, but right now I have a lot on my plate so it will take awhile for me to get to. If you want / need the changes more immediately, it would be a fairly simple pull request to implement the changes described there, and we would get it accepted and merged in a timely manner, so feel free to contribute the change!
